Looprac/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos
  resources :posts do
    member do
      put "like" => "posts#upvote"
       put "unlike" => "posts#downvote"
    end
  end

  resources :posts do
    resources :comments
  end

resources :users do
  resources :comments
end

resources :users do
  resources :posts
end

  root 'welcome#index'

  get "welcome/Registration"
  get "welcome/Profile"
  get "welcome/results"

end

Looprac/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

Looprac/app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 5 }
     
    acts_as_votable
    has_many :comments, dependent: :destroy
    belongs_to :user
end

Looprac/app/models/todo.rb
class Todo < ActiveRecord::Base
end

Looprac/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :comments
   has_many :posts
  acts_as_voter
end

Looprac/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password) }
        end
end

Looprac/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
	def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
 
  private
    def comment_params
      params.require(:comment).permit( :body)
    end
end

Looprac/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!, except: [ :index, :show ]
  before_filter :ensure_admin!, except: [ :index, :show, :upvote, :downvote ]
  

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def index
		@posts = Post.all
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
  		@post = Post.new(post_params)
        @post.user = current_user
  		if @post.save
    		redirect_to @post
  		else
    		render 'new'
  		end
	end

	def update
  		@post = Post.find(params[:id])
 
  		if @post.update(post_params)
    		redirect_to @post
  		else
    		render 'edit'
  		end
	end

	def destroy
  		@post = Post.find(params[:id])
  		@post.destroy
 
  		redirect_to posts_path
	end
    def upvote
     @post = Post.find(params[:id])
     @post.upvote_from current_user
     redirect_to @post
    end

    def downvote
    	@post = Post.find(params[:id])
    	@post.downvote_from current_user
    	redirect_to @post
    end
private
  def ensure_admin!
    unless current_user.admin?
      sign_out current_user
      alert

      redirect_to root_path

      return false
    end
  end
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

Looprac/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :notes)
    end
end

Looprac/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
	
	def Registration
	end

	def Profile
	end

	def results
	end
end

Looprac/app/helpers/application_helper.rb
module ApplicationHelper
end

Looprac/app/helpers/comments_helper.rb
module CommentsHelper
end

Looprac/app/helpers/posts_helper.rb
module PostsHelper
end

Looprac/app/helpers/todos_helper.rb
module TodosHelper
end

Looprac/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Looprac/app/views/comments/_comment.html.erb
<p>
  <strong>Name:</strong>
  <%= comment.user.username %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
	<% if user_signed_in? and current_user.admin? %>
		<%= link_to 'Destroy', [comment.post, comment],
			method: :delete,
			data: { confirm: 'Are you sure ya admin?' } %>
	<%end%>              
</p>

Looprac/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Leave Comment"%>
  </p>
<% end %>

Looprac/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Looprac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<div class="container-fluid">
		<div>

			<% if user_signed_in? %>
			<%= render 'shared/navigation_signed_in' %>
			<% else %>
			<%= render 'shared/navigation' %>
			<% end %>

		</div>
		<div>
			<% if notice %>
 		 		<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
  				<p class="alert alert-danger"><%= alert %></p>
			<% end %>
			<%= yield %>
		</div>
		<div>
			<%= render 'shared/footer' %>
		</div>
	</div>
</body>
</html>

Looprac/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

Looprac/app/views/posts/edit.html.erb
<h1>Edit post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

Looprac/app/views/posts/index.html.erb
<h1>Listing posts</h1>
<% if user_signed_in? and current_user.admin? %>
<%= link_to 'New Post', new_post_path %>
<% end %>

 <ul class="list-group">
  <% @posts.each do |post| %>
  <li class="list-group-item">
    
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
    
    <% if user_signed_in? and current_user.admin? %> 
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    <% end %>

    <button type="button" class="btn btn-info" aria-label="Left Align">
    <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= post.get_upvotes.size %></span>
  </button>

    
    <button type="button" class="btn btn-info" aria-label="Left Align">
    <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= post.get_downvotes.size %></span>
  </button>

</li>
  <% end %>

</ul>

Looprac/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

Looprac/app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>
<p>
  <strong>User:</strong>
  <%= @post.user.username %>
</p>

 

  <%= link_to like_post_path(@post), class: "like", method: :put do%>
    <button type="button" class="btn btn-info" aria-label="Left Align">
    <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= @post.get_upvotes.size %></span>
  </button>
  <% end %>
      
         <%=link_to unlike_post_path(@post), class: "like", method: :put do%>
    <button type="button" class="btn btn-info" aria-label="Left Align">
    <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
    <span class="badge"><%= @post.get_downvotes.size %></span>
  </button>
  <% end %>

	<h4>Share on Twitter or Facebook or G+</h4>
		<%= social_share_button_tag(@post.title, :popup => "true") %>

<% if user_signed_in? %>
  <h2>Comments</h2>
  <%= render @post.comments %>
 
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
<% end %> 

<%= link_to 'Back', posts_path %>

Looprac/app/views/shared/_breaks.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

Looprac/app/views/shared/_footer.html.erb
<nav class="navbar-inverse navbar-fixed-bottom nav-color">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-10"></div>
			<div class="col-md-2">
				<span class="glyphicon glyphicon-copyright-mark"></span>Looprac!
			</div>
		</div>
	</div>
</nav>

Looprac/app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default nav-color" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="/"><img src="/assets/looprac1.png" class="nav-img"></a>

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
    	
      <ul class="nav navbar-nav navbar-right">
        <div class="form-inline">
					<div class="form-group">
						<label class="sr-only" for="inputemail">Email</label>
						<input type="text" class="form-control" id="email" placeholder="Email">
					</div>
					<div class="form-group">
						<label class="sr-only" for="inputpw">Password</label>
						<input type="password" class="form-control" id="password" placeholder="Password">
					</div>
					<div class="checkbox">
						<label>
							<input type="checkbox">Remember me
						</label>
					</div>
					<div class="btn-group" role="group">
						<%= link_to 'Login', new_user_session_path, class: 'btn btn-default btn-sm navbar-btn', id: "signin" %>
						<%= link_to 'Signup', new_user_registration_path, class: 'btn btn-default btn-sm navbar-btn', id: "signup" %>

					</div>
				</div>
      </ul>
      <ul class="nav navbar-nav navbar-right">
    		
    	</ul>
    </div>
  </div>
</nav>

Looprac/app/views/shared/_navigation_signed_in.html.erb
<nav class="navbar navbar-default nav-color" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="/"><img src="/assets/looprac1.png" class="nav-img"></a>

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav nav-tabs navbar-nav navbar-right">
        <li>   <button type="button" class="btn btn-default"> <%= link_to 'Blog', :controller => "/posts" %> </li>
        <li class"dropdown active">
        	<a href="#" class="dropdown-toggle" data-toggle="dropdown">My Rides <span class="caret"></span></a>
        	<ul class="dropdown-menu">
        		<li><a href="#">Ride 1</a></li>
        		<li><a href="#">Ride 2</a></li>
        		<li><a href="#">Ride 3</a></li>
        	</ul>
        </li>

         <li class"dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img class="nav-prof-img" role="button" src="/assets/fbdefault.jpg"> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/welcome/Profile">View my Profile</a></li>
            <li><a href="#">Edit Profile</a></li>
            <li><%= link_to('Edit registration', edit_user_registration_path) %></li>
            <li><a href="#">Settings</a></li>
            <li class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>   </li>
          </ul>
        </li>
      </ul>

    </div>
  </div>
</nav>

Looprac/app/views/welcome/Profile.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Profile</title>
</head>
<body class="landing">
	<div class="container">
		<br></br>
		<div class="row">
        <div class="col-sm-3">
            <!--left col-->
            <ul class="list-group">
                <li class="list-group-item text-muted main-color" contenteditable="false">Profile</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="">Name</strong></span> Karim</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="">Joined</strong></span> 2.13.2014</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="">Last seen</strong></span> Yesterday</li>
            	<li class="list-group-item text-right"><span class="pull-left"><strong class="">Rank: </strong></span> Beginner</li>
            </ul>
            <div class="panel panel-default">
             <div class="panel-heading">
             	<p class="main-color">About my car</p>
            </div>
            <div class="panel-body">Car info goes here.

            </div>
        </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                	<p class="main-color">Social media</p>
                </div>
                <div class="panel-body"><a href="http://Facebook.com">
                	Facebook</a>
                </div>
            </div>
          
            <ul class="list-group">
                <li class="list-group-item text-muted main-color">Activity</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Rides offered</strong></span> 15</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Rides joined</strong></span> 13</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Rating</strong></span> 3.7</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong>Thumbs up</strong></span> 10</li>
            </ul>
        </div>
        <div class="col-sm-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                	<p class="main-color">Karim's Bio</p>
                </div>
                <div class="panel-body"> A description about me.

                </div>
            </div>
        </div>
	</div>
	<br></br>
	</div>
</body>
</html>

Looprac/app/views/welcome/Registration.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SignUp!</title>
</head>
<body class="landing">
	<br></br>
	<form class="form-horizontal">
	<div class="container"> 
		<div class="form-group">
			<label class="col-sm-2 control-label" for="inputEmail">Email Address:</label>
			<div class="col-sm-4">
				<input class="form-control" type="email" id="inputEmail" placeholder="Enter Email">
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label" for="inputUsername">UserName:</label>
			<div class="col-sm-3">
				<input class="form-control" type="text" placeholder="Pick a username"></input>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label" for="inputPassword">Password:</label>
			<div class="col-sm-3">
				<input class="form-control" type="password" placeholder="Enter a password"></input>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label" for="inputPassword">Confirm Password:</label>
			<div class="col-sm-3">
				<input class="form-control" type="password" placeholder="Retype your password"></input>
			</div>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col-sm-10 col-sm-offset-2">
					<div class="checkbox">
						<label>
							<input type="checkbox"> I want to receive updates about the site!
						</label>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-10 col-sm-offset-2">
					<div class="checkbox">
						<label>
							<input type="checkbox"> I agree to the <a href="#">terms and conditions</a>.
						</label>
					</div>
				</div>
			</div>
		</div>
		
		<div class="form-group">
			<div class="col-sm-10 col-sm-offset-2">
				<button type="submit" class="btn btn-success">
					<i class="glyphicon glyphicon-ok"></i>SignUp!
				</button>
			</div>
		</div>
	</div>
</form class="landing">
</body>
</html>

Looprac/app/views/welcome/_search_rides.html.erb
<div class="container" id="main-container">
	<br>
	
	<div class="row-fluid">
		<div class="col-md-6 center-block center">
			<form class="form-inline block">
				<div class="input-group">
					<span class="input-group-addon glyphicon glyphicon-arrow-left" id="from"></span>
					<input type="text" class="form-control" placeholder="from..">
				</div>
				<div class="input-group">
					<span class="input-group-addon glyphicon glyphicon-arrow-right" id="to"></span>
					<input type="text" class="form-control" placeholder="to..">
				</div>
			</form>
		</div>
	</div>
	<div class="row-fluid">
		<div class="col-sm-6 col-sm-offset-6">
			<a class="btn-wide" href="#">Advanced Search</a>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-3 center-block center">
			<%= link_to '/welcome/results', class: 'btn btn-wide btn-success' do%>
  				<i class="glyphicon glyphicon-search"></i>Search
			<% end %>
		</div>	
	</div>
</div>

Looprac/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Landing Page</title>
</head>
<body class="landing">

	<div class="container">
	<br>
		<% if user_signed_in? %>
			<p> Signed in as <%= current_user.email %></p>
		<% end %>
		<div class="jumbotron">
			<h1>Some homepage stuff goes here</h1>
			<%= render 'shared/breaks' %>
		</div>
	</div>
	<br >
	<%= render 'search_rides' %>
	<br></br>
</body>
</html>

Looprac/app/views/welcome/results.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body class="landing">
	<div class="container" id="main-container">
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="narvbar-header">
					<a class="navbar-brand" href="#">
						<span class="glyphicon glyphicon-search"></span>
					</a>
				</div>
				<ul class="nav navbar-nav">
					<li>
						<%= link_to 'Search Again','/', class: 'btn btn-block'%>
					</li>
					<li>
						<%= link_to 'Advanced Search','#', class: 'btn btn-block'%>
					</li>

				</ul>

				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Sort By <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="#">Reputation</a></li>
							<li><a href="#">Availability</a></li>
							<li><a href="#">Distance</a></li>
							<li class="divider"></li>
							<li><a href="#">Reset Sort</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</nav>
		<div class="jumbotron">
			<h1>Search Results</h1>
			<%= render 'shared/breaks' %>
			<%= render 'shared/breaks' %>
		</div>

		<nav class="col-sm-12 col-sm-offset-4">
			<ul class="pagination">
			    <li>
			      <a href="#" aria-label="Previous">
			        <span class="glyphicon glyphicon-arrow-left"></span> Older
			      </a>
				</li>
				<li><a href="#">1</a></li>
			    <li><a href="#">2</a></li>
			    <li><a href="#">3</a></li>
			    <li><a href="#">4</a></li>
			    <li><a href="#">5</a></li>
			    <li>
			    	<a href="#" aria-label="Previous">
			       	 	Newer <span class="glyphicon glyphicon-arrow-right"></span> 
			      </a>
			    </li>
  			</ul>
		</nav>

	</div>
</body>
</html>