blog/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "welcome#index"
  get 'pages', to: 'pages#index'
  
  get 'pages/atarek'
  get 'pages/aya'
  get 'pages/walid'
  get 'pages/tarek'
  get 'pages/alfy'
  get 'pages/karim'
  get 'pages/rana'
  get 'pages/amy'
  
  resources :articles do
    resources :youtubes
  end
  resources :articles do
    resources :photos
  end
   resources :articles  do
    resources :comments 
  end
   resources :comments do
     resources :sub_comments
  end
  
  devise_scope :user do
    get '/logout',  :to => 'users/sessions#destroy'
  end

  devise_scope :user do
    get '/login',  :to => 'users/sessions#create'
  end

  devise_scope :user do
    get '/edit_acc',  :to => 'users/registrations#edit'
  end

  devise_scope :user do
    get '/signup',  :to => 'users/registrations#new'
  end

  
end

blog/app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
	                  length: { minimum: 5}
	has_many :photos, dependent: :destroy
	has_many :youtubes, dependent: :destroy
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  has_many :sub_comments, dependent: :destroy
  validates :commenter , presence: true
end

blog/app/models/photo.rb
class Photo < ActiveRecord::Base
	
  belongs_to :article
 mount_uploader :image, ImageUploader
 
end

blog/app/models/sub_comment.rb
class SubComment < ActiveRecord::Base
  belongs_to :comment
  validates :commenter , presence: true
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog/app/models/youtube.rb
class Youtube < ActiveRecord::Base
  belongs_to :article
end

blog/app/controllers/blog_controller.rb
class BlogController < ApplicationController

	before_action :authenticate_user!

end

blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
	
	def alfy
	end

	def walid
	end

	def aya
	end
    
    def rana
    end

    def atarek
    end

    def tarek
    end

    def amy
    end
end

blog/app/controllers/photos_controller.rb
class PhotosController < BlogController
	def index
	end
	def create
		@article = Article.find(params[:article_id])
		@photo = @article.photos.create(photo_params)
		redirect_to article_path(@article)
	end
    def destroy
		@article = Article.find(params[:article_id])
		@photo = @article.photos.find(params[:id])
		@photo.destroy
		redirect_to article_path(@article)
	end
	private
	def photo_params
		params.require(:photo).permit(:image)
	end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/blog_helper.rb
module BlogHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/pages_helper.rb
module PagesHelper
end

blog/app/helpers/photos_helper.rb
module PhotosHelper
end

blog/app/helpers/sub_comments_helper.rb
module SubCommentsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/helpers/youtubes_helper.rb
module YoutubesHelper
	def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="sidebar">
	<ul>
			<li class="category">Twikly</li>
		</ul>

		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Blog", :controller => "/articles" %>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="https://twitter.com/TwiklyOfficial">Twitter</a></li>
			<li><a href="http://instagram.com/twiklyofficial">Instagram</a></li>
			<li><a href="https://facebook.com/TwiklyOfficial">Facebook</a></li>
			<li><a href="mailto:TwiklyOfficial@gmail.com">Email</a></li>
		</ul>

		<% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
		<% end %>
	</div>

	<div id="main_content">
    	<div id="header">
     	 <p>All posts</p>
 
      <div class="buttons">
        <% if current_user.try(:auth?) %>
          <button class="button"><%= link_to "New Article", new_article_path %>
        <% end %>
        <button class="button"><%= link_to "Our Members", :controller  => "/pages", :action => "index" %>
        <button class="button"><%= render 'devise/menu/login_tools' %>
        <button class="button"><%= render 'devise/menu/registration_items' %>
      </div>
    </div>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
</div>
</body>
</html>

blog/app/views/pages/alfy.html.erb
<div id="page_wrapper">
  <img src="/assets/newalfy.jpg" width="250" height="250">
  <br></br>
  <h3>Mohamed El-Alfy</h3>
  <p>Alfy. Mohamed El-Alfy. When the GUC is not sucking the life out of me, I get the chance to play FIFA, watch football, enjoy El Ahwa and read. </p>
</div>

blog/app/views/pages/amy.html.erb
<div id="page_wrapper">
	<h3>Amy Elmossly</h3>
	<img src="/assets/newamy.jpg" width="200" height="200">
  	<br></br>
  	<p>Hi ! I'm Amy Mohamed El-Mossly studying computer science in the GUC. Im origionally from cairo but i live in hurghada now for 15years in hurghada. I like hand crafts reading and playing squash.</p>
</div>

blog/app/views/pages/atarek.html.erb
<div id="page_wrapper">
	<h3>Ahmed Tarek</h3>
	<img src="/assets/newatarek.jpg" width="200" height="200">
  	<br></br>
  	<p>I'm Ahmed Tarek Kamel Abdelfattah Helmy. I'm 20 years old. I LOVE food, travelling and adventures. Friends is the best series ever made. A proud member of TEDxGUC. </p>
</div>

blog/app/views/pages/aya.html.erb
<div id="page_wrapper">
  <img src="/assets/newaya.jpg" width="200" height="200">
  <br></br>
  <h3>Aya Amr</h3>
  <p>Hello, I'm Ayatallah Amr. I'm 20 years old Junior ACMer and studying computer science and engineering at the GUC. I enjoy meeting new people, reading, aerobics and GUESS WHAT?? Coding.</p>
  </div>

blog/app/views/pages/index.html.erb
	<div class ="post_wrapper">
		<h2 class="title"><%= link_to "Ahmed Tarek", :controller => :pages, :action => :atarek  %></h2>
	</div>
	<div class ="post_wrapper">
		<h2 class="title"><%= link_to "Ahmed Walid", :controller => :pages, :action => :walid %></h2>
	</div>
	<div class ="post_wrapper">
		<h2 class="title"><%= link_to "Amy Elmossly", :controller => :pages, :action => :amy %></h2>
	</div>
	<div class ="post_wrapper">
		<h2 class="title"><%= link_to "Aya Amr", :controller => :pages, :action => :aya %></h2>
	</div>
	<div class ="post_wrapper">
		<h2 class="title"><%= link_to "Karim Taha", :controller => :pages, :action => :karim   %></h2>
	</div>
	<div class ="post_wrapper">
		<h2 class="title"><%= link_to "Tarek El-Beih", :controller => :pages, :action => :tarek %></h2>
	</div>
	<div class ="post_wrapper">
		<h2 class="title"><%= link_to "Mohamed El-Alfy", :controller => :pages, :action => :alfy  %></h2>
	</div>
	<div class ="post_wrapper">
		<h2 class="title"><%= link_to "Rana El-Fedawy", :controller => :pages, :action => :rana  %></h2>
	</div>

blog/app/views/pages/karim.html.erb
<div id="page_wrapper">
  <img src="/assets/newtaha.jpg" width="300" height="300">
  <br></br>
  <h3>Karim Taha</h3>
  <p>Hi, my name is Karim Mohamed Taha. I'm 20 years old and I study Computer Science and engineering at the German University in Cairo. I enjoy listening to music and watching football games.
</p>
 </div>

blog/app/views/pages/rana.html.erb
<div id="page_wrapper">
   <img src="/assets/newrana.jpg" width="200" height="200">
  <h3>Rana El-Fedawy</h3>
  <p>I'm Rana Saleh Elfedawy. I'm  20 years old. I like swimming and tennis.</p>
 </div>

blog/app/views/pages/tarek.html.erb
<div id="page_wrapper">
  <img src="/assets/tarek.jpg" width="200" height="200">
  <br></br>
  <h3>Tarek El-beih</h3>
  <p>My Real name is ISPoonJelly, Tarek is just a nickname.</p>
  </div>

blog/app/views/pages/walid.html.erb
<div id="page_wrapper">
  <img src="/assets/images/newwalid.jpg" width="400" height="400">
  <br></br>
  <h3>Ahmed Walid</h3>
  <p>I'm Ahmed Walid Ahmed, I'm 20 years old and I like Gaming and Football.</p>
  </div>